### ISSUE TITLE
Issues after last refactoring on dev branch

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#168]
* I can not open preferences window;
* Only the main node is displayed;
* On transaction tab, on upper dates fields it is written: `jj/01/amamamam` and `jj/07/pmpmpmpm`.

**Comment by Insoleet** [comment]
Can you take some screenshots please ?

Can you get us some traces to debug it ? ( python main.py -d ... ) ?

Thanks !

**Comment by M5oul** [comment]
* I get those errors when invoke preference window in debug mod:
```bash
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/mainwindow.py", line 173, in open_preferences_dialog
    dialog = PreferencesDialog(self.app)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/gui/preferences.py", line 39, in __init__
    self.combo_language.addItem(lang)
AttributeError: 'PreferencesDialog' object has no attribute 'combo_language'
DEBUG:__init__:Callback timer fired, calling <Handle Future._set_result_unless_cancelled(None)>
DEBUG:__init__:Registering callback <bound method Task._wakeup of <Task pending coro=<discover_network() running at /home/moul/Documents/cutecoin/build/src/cutecoin/core/net/network.py:203> wait_for=<Future finished result=None>>> to be invoked with arguments (<Future finished result=None>,) after 0 second(s)
DEBUG:__init__:Adding callback <Handle Task._wakeup(<Future finished result=None>)> with delay 0
DEBUG:__init__:Callback timer fired, calling <Handle Task._wakeup(<Future finished result=None>)>
DEBUG:node:Refresh block
```
* Only the main node is displayed:
![network_tab_display_issue](https://cloud.githubusercontent.com/assets/4758871/8555359/e9e38bd8-24ef-11e5-90e3-6a12792834b6.png)

* Date display issue on transaction tab:
![tx_tab_date_display_issue](https://cloud.githubusercontent.com/assets/4758871/8555375/027089a8-24f0-11e5-8c42-052a7069e80b.png)

* Also, multiple notifications each ~10/15 minutes:
![noticifications_issue](https://cloud.githubusercontent.com/assets/4758871/8555381/0ac7c562-24f0-11e5-9847-207667ed4a1f.png)

**Comment by M5oul** [comment]
Also, logs when launched without debug mod:
```bash
Debug enabled : False
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/net/network.py", line 212, in handle_new_node
    node = Node.from_peer(self.network_manager, self.currency, peer, pubkey)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/net/node.py", line 117, in from_peer
    logging.debug("Node from peer : {:}".format(str(node)))
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/net/node.py", line 448, in __str__
    return ','.join([str(self.pubkey), str(self.endpoint.server), str(self.endpoint.port), str(self.block),
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/net/node.py", line 199, in endpoint
    return next((e for e in self._endpoints if type(e) is BMAEndpoint))
StopIteration
Traceback (most recent call last):
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/net/network.py", line 212, in handle_new_node
    node = Node.from_peer(self.network_manager, self.currency, peer, pubkey)
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/net/node.py", line 117, in from_peer
    logging.debug("Node from peer : {:}".format(str(node)))
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/net/node.py", line 448, in __str__
    return ','.join([str(self.pubkey), str(self.endpoint.server), str(self.endpoint.port), str(self.block),
  File "/home/moul/Documents/cutecoin/build/src/cutecoin/core/net/node.py", line 199, in endpoint
    return next((e for e in self._endpoints if type(e) is BMAEndpoint))
StopIteration
```

**Comment by Insoleet** [comment]
You should run gen_resources.py and try again !

**Comment by M5oul** [comment]
I am running this Shell script every time I launch CuteCoin:
```bash
rm -rf /home/moul/.config/cutecoin/m4oul/__cache__
cd build
git pull http://github.com/ucoin-io/cutecoin/ dev
python3 gen_resources.py
python3 gen_translations.py
python3 src/cutecoin/main.py
```

**Comment by Insoleet** [comment]
The preferences bug is weird, and I can't reproduce it.  
Do "python3 gen_resources.py" executes without any problem ? And also for "python3 gen_translations.py"...

Also 
> git pull http://github.com/ucoin-io/cutecoin/ dev

Shouldn't it be .. ?
> git pull origin dev

 The bug "StopIteration" is caused because self._endpoints is empty. Could you copy the file "meta_brouzouf_network" present in your __cache__ folder after the errors are shown and cutecoin is closed ?

What is happening by your side is definitely strange. We will need some investigation. @vtexier , could you try and describe how it runs if you try by your side ?

**Comment by vtexier** [comment]
* Notifications are ok.
* Preferences popup is ok.
* Transaction dates are ok.

Bugs : 
* Only main node appear in network tab.
* I got the same StopIteration bug in console when starting cutecoin : 

>
Traceback (most recent call last):
  File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/core/net/network.py", line 212, in handle_new_node
    node = Node.from_peer(self.network_manager, self.currency, peer, pubkey)
  File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/core/net/node.py", line 117, in from_peer
    logging.debug("Node from peer : {:}".format(str(node)))
  File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/core/net/node.py", line 448, in __str__
    return ','.join([str(self.pubkey), str(self.endpoint.server), str(self.endpoint.port), str(self.block),
  File "/home/vit/Documents/dev/python/cutecoin/src/cutecoin/core/net/node.py", line 199, in endpoint
    return next((e for e in self._endpoints if type(e) is BMAEndpoint))
StopIteration

The meta_brouzouf_network file : 
>
{
    "network": [
        {
            "block": 22211,
            "currency": "meta_brouzouf",
            "endpoints": [
                "BASIC_MERKLED_API metab.ucoin.io 88.163.127.43 9201"
            ],
            "last_change": 1436347577.9436853,
            "pubkey": "HnFcSms8jzwngtVomTTnzudZx7SHUQY8sVE1y8yBmULk",
            "state": 1,
            "uid": "cgeek"
        }
    ],
    "version": "0.10.0"
}

**Comment by M5oul** [comment]
I did a new clone, those issues are fixed:
* Date display issue on transaction tab:
* Now, I can display bloc hour.

But, there is also those issues:
* Can not open preferences window;
* Only the main node is displayed;
* Multiple notifications each ~10/15 minutes.

I have change the command to `git pull origin master`.

I will give you more information later…

**Comment by Insoleet** [comment]
The command should be "git pull origin dev" not master.

The preferences window still buggy is really weird. Can you copy paste the file "preferences_uic.py" in "src/cutecoin/gen_resources/" ?

**Comment by Insoleet** [comment]
Last commits should have fixed most of these bugs. Can you try again please ?

**Comment by M5oul** [comment]
I wrote a mistake, I am well doing `git pull origin dev`.

With latest commits:
* I can see tree nodes on network tab;
* I get only one notification about expiration member.

But:
* I still can not open preference window before and after pasting `src/cutecoin/preferences_uic.py` in `gen_resources.py`.

**Comment by Insoleet** [comment]
Sorry, I wrote too fast something stupid haha.

Please execute the following command : 
> git checkout gen_resources.py

Then : 
> python3 gen_resources.py

Then, copy the logs of gen_resources here, try to start cutecoin again and open preferences. If that still doesn't work, please copy the file "src/cutecoin/gen_resources/preferences_uic.py" here, so we can check its content.

**Comment by M5oul** [comment]
Finaly, there is an issue with PyQt version:
```bash
$ git checkout gen_resources.py
[moul@localhost build]$ python3 gen_resources.py
/home/moul/Documents/cutecoin/build/res/ui/import_account.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/import_account_uic.py
/home/moul/Documents/cutecoin/build/res/ui/transactions_tab.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/transactions_tab_uic.py
/home/moul/Documents/cutecoin/build/res/ui/informations_tab.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/informations_tab_uic.py
/home/moul/Documents/cutecoin/build/res/ui/contact.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/contact_uic.py
/home/moul/Documents/cutecoin/build/res/ui/account_cfg.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/account_cfg_uic.py
/home/moul/Documents/cutecoin/build/res/ui/member.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/member_uic.py
/home/moul/Documents/cutecoin/build/res/ui/create_wallet.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/create_wallet_uic.py
/home/moul/Documents/cutecoin/build/res/ui/preferences.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/preferences_uic.py
/home/moul/Documents/cutecoin/build/res/ui/community_cfg.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/community_cfg_uic.py
/home/moul/Documents/cutecoin/build/res/ui/currency_tab.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/currency_tab_uic.py
/home/moul/Documents/cutecoin/build/res/ui/about.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/about_uic.py
/home/moul/Documents/cutecoin/build/res/ui/toast.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/toast_uic.py
/home/moul/Documents/cutecoin/build/res/ui/community_tab.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/community_tab_uic.py
/home/moul/Documents/cutecoin/build/res/ui/homescreen.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/homescreen_uic.py
/home/moul/Documents/cutecoin/build/res/ui/wot_tab.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/wot_tab_uic.py
/home/moul/Documents/cutecoin/build/res/ui/network_tab.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/network_tab_uic.py
/home/moul/Documents/cutecoin/build/res/ui/wallets_tab.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/wallets_tab_uic.py
/home/moul/Documents/cutecoin/build/res/ui/certification.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/certification_uic.py
/home/moul/Documents/cutecoin/build/res/ui/password_asker.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/password_asker_uic.py
/home/moul/Documents/cutecoin/build/res/ui/transfer.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/transfer_uic.py
/home/moul/Documents/cutecoin/build/res/ui/mainwindow.ui >> /home/moul/Documents/cutecoin/build/src/cutecoin/gen_resources/mainwindow_uic.py
/home/moul/Documents/cutecoin/build/res/icons/icons.qrc >> /home/moul/Documents/cutecoin/build/src/icons_rc.py
An unexpected error occurred.
Check that you are using the latest version of PyQt5 and send an error report to
support@riverbankcomputing.com, including the following information:

  * your version of PyQt (5.4.1)
  * the UI file that caused this error
  * the debug output of pyuic5 (use the -d flag when calling pyuic5)
```

**Comment by Insoleet** [comment]
Can you do the following and copy the output please ?

> pyuic5 -d res/ui/preferences.ui

**Comment by M5oul** [comment]
```bash
pyuic5 -d res/ui/preferences.ui
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/ui/preferences.ui'
#
# Created by: PyQt5 UI code generator 5.4.1
#
# WARNING! All changes made in this file will be lost!

PyQt5.uic.uiparser: UI version is 4.0
PyQt5.uic.uiparser: uiname is PreferencesDialog
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName("PreferencesDialog")
PyQt5.uic.uiparser: toplevel widget is QDialog
PyQt5.uic.properties: setting property geometry
        PreferencesDialog.resize(443, 315)
PyQt5.uic.properties: setting property windowTitle
PyQt5.uic.uiparser: push QDialog PreferencesDialog
        self.verticalLayout = QtWidgets.QVBoxLayout(PreferencesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
PyQt5.uic.uiparser: push QVBoxLayout verticalLayout
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
PyQt5.uic.properties: setting property topMargin
PyQt5.uic.properties: setting property pyuicContentsMargins
        self.horizontalLayout_2.setContentsMargins(-1, 6, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
PyQt5.uic.uiparser: push QHBoxLayout horizontalLayout_2
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
PyQt5.uic.properties: setting property leftMargin
PyQt5.uic.properties: setting property pyuicContentsMargins
        self.verticalLayout_6.setContentsMargins(6, -1, -1, -1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
PyQt5.uic.uiparser: push QVBoxLayout verticalLayout_6
        self.button_app = QtWidgets.QPushButton(PreferencesDialog)
PyQt5.uic.properties: setting property text
        self.button_app.setText("")
PyQt5.uic.properties: setting property icon
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/settings_app_icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_app.setIcon(icon)
PyQt5.uic.properties: setting property iconSize
        self.button_app.setIconSize(QtCore.QSize(65, 65))
PyQt5.uic.properties: setting property flat
        self.button_app.setFlat(True)
        self.button_app.setObjectName("button_app")
PyQt5.uic.uiparser: push QPushButton button_app
PyQt5.uic.uiparser: pop widget QPushButton button_app
PyQt5.uic.uiparser: new topwidget PreferencesDialog
        self.verticalLayout_6.addWidget(self.button_app)
        self.button_display = QtWidgets.QPushButton(PreferencesDialog)
PyQt5.uic.properties: setting property text
        self.button_display.setText("")
PyQt5.uic.properties: setting property icon
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/settings_display_icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_display.setIcon(icon1)
PyQt5.uic.properties: setting property iconSize
        self.button_display.setIconSize(QtCore.QSize(65, 65))
PyQt5.uic.properties: setting property flat
        self.button_display.setFlat(True)
        self.button_display.setObjectName("button_display")
PyQt5.uic.uiparser: push QPushButton button_display
PyQt5.uic.uiparser: pop widget QPushButton button_display
PyQt5.uic.uiparser: new topwidget PreferencesDialog
        self.verticalLayout_6.addWidget(self.button_display)
        self.button_network = QtWidgets.QPushButton(PreferencesDialog)
PyQt5.uic.properties: setting property text
        self.button_network.setText("")
PyQt5.uic.properties: setting property icon
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/settings_network_icon"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_network.setIcon(icon2)
PyQt5.uic.properties: setting property iconSize
        self.button_network.setIconSize(QtCore.QSize(65, 65))
PyQt5.uic.properties: setting property flat
        self.button_network.setFlat(True)
        self.button_network.setObjectName("button_network")
PyQt5.uic.uiparser: push QPushButton button_network
PyQt5.uic.uiparser: pop widget QPushButton button_network
PyQt5.uic.uiparser: new topwidget PreferencesDialog
        self.verticalLayout_6.addWidget(self.button_network)
PyQt5.uic.uiparser: pop layout QVBoxLayout verticalLayout_6
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.line = QtWidgets.QFrame(PreferencesDialog)
PyQt5.uic.properties: setting property orientation
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
PyQt5.uic.uiparser: push QFrame line
PyQt5.uic.uiparser: pop widget QFrame line
PyQt5.uic.uiparser: new topwidget PreferencesDialog
        self.horizontalLayout_2.addWidget(self.line)
        self.stackedWidget = QtWidgets.QStackedWidget(PreferencesDialog)
PyQt5.uic.properties: setting property currentIndex
        self.stackedWidget.setObjectName("stackedWidget")
PyQt5.uic.uiparser: push QStackedWidget stackedWidget
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
PyQt5.uic.uiparser: push QWidget page
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
PyQt5.uic.uiparser: push QVBoxLayout verticalLayout_7
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
PyQt5.uic.uiparser: push QHBoxLayout horizontalLayout
        self.label = QtWidgets.QLabel(self.page)
PyQt5.uic.properties: setting property text
        self.label.setObjectName("label")
PyQt5.uic.uiparser: push QLabel label
PyQt5.uic.uiparser: pop widget QLabel label
PyQt5.uic.uiparser: new topwidget self.page
        self.horizontalLayout.addWidget(self.label)
        self.combo_account = QtWidgets.QComboBox(self.page)
        self.combo_account.setObjectName("combo_account")
PyQt5.uic.uiparser: push QComboBox combo_account
PyQt5.uic.uiparser: pop widget QComboBox combo_account
PyQt5.uic.uiparser: new topwidget self.page
        self.horizontalLayout.addWidget(self.combo_account)
PyQt5.uic.uiparser: pop layout QHBoxLayout horizontalLayout
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
PyQt5.uic.uiparser: push QHBoxLayout horizontalLayout_3
        self.label_3 = QtWidgets.QLabel(self.page)
PyQt5.uic.properties: setting property text
PyQt5.uic.properties: setting property buddy
        self.label_3.setObjectName("label_3")
PyQt5.uic.uiparser: push QLabel label_3
PyQt5.uic.uiparser: pop widget QLabel label_3
PyQt5.uic.uiparser: new topwidget self.page
        self.horizontalLayout_3.addWidget(self.label_3)
        self.combo_referential = QtWidgets.QComboBox(self.page)
        self.combo_referential.setObjectName("combo_referential")
PyQt5.uic.uiparser: push QComboBox combo_referential
PyQt5.uic.uiparser: pop widget QComboBox combo_referential
PyQt5.uic.uiparser: new topwidget self.page
        self.horizontalLayout_3.addWidget(self.combo_referential)
PyQt5.uic.uiparser: pop layout QHBoxLayout horizontalLayout_3
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.line_2 = QtWidgets.QFrame(self.page)
PyQt5.uic.properties: setting property orientation
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
PyQt5.uic.uiparser: push QFrame line_2
PyQt5.uic.uiparser: pop widget QFrame line_2
PyQt5.uic.uiparser: new topwidget self.page
        self.verticalLayout_7.addWidget(self.line_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
PyQt5.uic.uiparser: push QHBoxLayout horizontalLayout_4
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.checkbox_expertmode = QtWidgets.QCheckBox(self.page)
PyQt5.uic.properties: setting property text
        self.checkbox_expertmode.setObjectName("checkbox_expertmode")
PyQt5.uic.uiparser: push QCheckBox checkbox_expertmode
PyQt5.uic.uiparser: pop widget QCheckBox checkbox_expertmode
PyQt5.uic.uiparser: new topwidget self.page
        self.horizontalLayout_4.addWidget(self.checkbox_expertmode)
PyQt5.uic.uiparser: pop layout QHBoxLayout horizontalLayout_4
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem1)
PyQt5.uic.uiparser: pop layout QVBoxLayout verticalLayout_7
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/port_v2/invoke.py", line 34, in invoke
    exit_status = driver.invoke()
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/driver.py", line 59, in invoke
    self._generate()
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/driver.py", line 93, in _generate
    self._opts.from_imports, self._opts.resource_suffix)
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/__init__.py", line 162, in compileUi
    winfo = compiler.UICompiler().compileUi(uifile, pyfile, from_imports, resource_suffix)
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/Compiler/compiler.py", line 110, in compileUi
    w = self.parse(input_stream, resource_suffix)
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/uiparser.py", line 999, in parse
    actor(elem)
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/uiparser.py", line 811, in createUserInterface
    self.traverseWidgetTree(elem)
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/uiparser.py", line 789, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/uiparser.py", line 496, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/uiparser.py", line 789, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/uiparser.py", line 539, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/uiparser.py", line 789, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/uiparser.py", line 496, in createLayout
    self.traverseWidgetTree(elem)
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/uiparser.py", line 789, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/uiparser.py", line 539, in handleItem
    self.traverseWidgetTree(elem)
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/uiparser.py", line 789, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/uiparser.py", line 256, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/uiparser.py", line 789, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/uiparser.py", line 256, in createWidget
    self.traverseWidgetTree(elem)
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/uiparser.py", line 789, in traverseWidgetTree
    handler(self, child)
  File "/usr/lib64/python2.7/site-packages/PyQt5/uic/uiparser.py", line 757, in setZOrder
    getattr(self.toplevelWidget, elem.text).raise_()
TypeError: getattr(): attribute name must be string
```

**Comment by Insoleet** [comment]
Wow weird bug.
It seems like it's a bug from an older version of pyuic5.
http://www.riverbankcomputing.com/pipermail/pyqt/2015-March/035651.html

Can you try to update it ?

**Comment by Insoleet** [comment]
I manually removed zorder elements.
https://github.com/ucoin-io/cutecoin/commit/1f883dc555422e9055406082e28e1d5ded5f5a2f

It should fix your problem but it's not a good fix. Just to confirm it's a pyuic bug.

**Comment by M5oul** [comment]
Preferences window works without zorder elements :)

**Comment by Insoleet** [comment]
Ok. You should find a way to upgrade pyuic5 for next time zorder elements appears in the ui files.

If no more problems are present, I think you can close this issue. :)

**Comment by M5oul** [comment]
Ok,
I still got multiple notifications about expiration member.

**Comment by M5oul** [comment]
Those notifications happens when getting new blocks, when there is a loading bar on transactions tab.

**Comment by Insoleet** [comment]
This is totally normal then. At the moment, each new block received checks for membership state and warn the user is necessary.

**Comment by M5oul** [comment]
Ah, ok. I would prefer it warn only one time. For instance, at launch. May be it could be a parameter.

**Comment by vtexier** [comment]
When alerts were as window popup, they were only at start, because it is very annoying to have it on each block.
But I think that the best behaviour is to have the alert "one time per session". We must keep track of the alerts we have made, and don't repeat it until cutecoin is restarted.

**Comment by Insoleet** [comment]
And what about clients never closed ?

**Comment by M5oul** [comment]
What?

**Comment by Insoleet** [comment]
Desktop clients are sometimes never closed. No notification would be pushed ?

**Comment by M5oul** [comment]
Yep, one notification per day would be great :+1:
