### ISSUE TITLE
UD creation issue

### ISSUE THREAD

**Issue by M5oul** [ucoin-io/cutecoin#172]
UD creation is displayed every two days:
![du_creation_issue](https://cloud.githubusercontent.com/assets/4758871/8596597/92df1872-2650-11e5-9a1f-bf9794b6c60e.png)

**Comment by Insoleet** [comment]
It's probably a ucoin bug. @c-geek  what do you think ?

**Comment by vtexier** [comment]
Same bug for me : 
* Some UD are missing in history.
* UD appear in Payment column, should appear in Deposit column.

http://metab.ucoin.io:9201/ud/history/RdrHvL179Rw62UuyBrqy2M1crx7RPajaViBatS59EGS

compare to cutecoin : 

![cutecoin_bug_ud](https://cloud.githubusercontent.com/assets/2174016/8602798/9ad204c6-2674-11e5-87ba-8e617f03f6a1.png)

**Comment by Insoleet** [comment]
Should be fixed now. Can you check ?

**Comment by M5oul** [comment]
Seems ok to me.

**Comment by vtexier** [comment]
There is still a problem for me. The UD at 07/07/2015 with amount of 104058529 is missing from the transactions list.
It is missing in the cache too, except in sources : 

>
grep -r 104058529 ~/.config/cutecoin/vit/__cache__/RdrHvL179Rw62UuyBrqy2M1crx7RPajaViBatS59EGS_wal 
                "inline": "0:D:22099:00004A2B80E3ACEEB2101D6AD55A803F95430165:104058529\n"

But the UD is returned well by the request http://metab.ucoin.io:9201/ud/history/RdrHvL179Rw62UuyBrqy2M1crx7RPajaViBatS59EGS

**Comment by vtexier** [comment]
Another bug : if cutecoin is open when the new UD arrive, it is not added in the transactions list. Need to quit properly to save it in the cache, and restart to see it.

**Comment by Insoleet** [comment]
Everything should be ok now.
